# Generated by Django 5.0.6 on 2024-05-23 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0003_patient_id_alter_patient_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(auto_now_add=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'requested'), (1, 'accepted'), (2, 'ongoing'), (3, 'ended')], default=0)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.patient')),
            ],
            options={
                'ordering': ['starttime'],
            },
        ),
    ]
