# Generated by Django 5.0.6 on 2024-05-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
