# Generated by Django 5.0.6 on 2024-05-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_patient_id_alter_patient_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
